#!/usr/bin/env python2
import urllib2
import xml.etree.ElementTree
from sys import argv

if len(argv) < 3:
    print argv[0], "<url> <episode>"
    exit()

data = urllib2.urlopen(argv[1]).read()
e = xml.etree.ElementTree.fromstring(data)

for item in e[0].findall('item'):
    if item.find('enclosure') is not None:
        if argv[2] in item.find('title').text:
            stream =  item.find('enclosure').get('url')
            break

print stream
